server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.247.184.35:8899/app-test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: write
    password: write

  datasource2:
    url: jdbc:mysql://43.247.184.35:8899/app-test1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: write
    password: write


info:
  mp:
    configs:
      - driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://43.247.184.35:8899/app-test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: write
        password: write

      - driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://43.247.184.35:8899/app-test1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: write
        password: write